"use client";

import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Lightbulb } from "lucide-react";
import { approveIdea, rejectIdea } from "./actions";

interface ContentIdea {
	_id: string;
	_createdAt: string;
	title: string;
	status: "new" | "approved" | "rejected" | "published";
	source?: string;
	category?: string;
}

const statusConfig: Record<
	string,
	{ label: string; className: string }
> = {
	new: {
		label: "New",
		className: "bg-blue-100 text-blue-800 hover:bg-blue-100 dark:bg-blue-900 dark:text-blue-300",
	},
	approved: {
		label: "Approved",
		className: "bg-green-100 text-green-800 hover:bg-green-100 dark:bg-green-900 dark:text-green-300",
	},
	rejected: {
		label: "Rejected",
		className: "bg-red-100 text-red-800 hover:bg-red-100 dark:bg-red-900 dark:text-red-300",
	},
	published: {
		label: "Published",
		className: "bg-purple-100 text-purple-800 hover:bg-purple-100 dark:bg-purple-900 dark:text-purple-300",
	},
};

function StatusBadge({ status }: { status: string }) {
	const config = statusConfig[status] ?? {
		label: status,
		className: "",
	};
	return (
		<Badge variant="outline" className={config.className}>
			{config.label}
		</Badge>
	);
}

function formatDate(dateString: string) {
	return new Date(dateString).toLocaleDateString("en-US", {
		month: "short",
		day: "numeric",
		year: "numeric",
	});
}

export function ContentIdeasTable({ ideas }: { ideas: ContentIdea[] }) {
	if (ideas.length === 0) {
		return (
			<div className="flex flex-col items-center justify-center rounded-lg border border-dashed p-12 text-center">
				<Lightbulb className="h-12 w-12 text-muted-foreground/50" />
				<h3 className="mt-4 text-lg font-semibold">No content ideas yet</h3>
				<p className="mt-2 text-sm text-muted-foreground">
					Content ideas will appear here once they&apos;re created in Sanity
					or generated by the automation pipeline.
				</p>
			</div>
		);
	}

	return (
		<div className="rounded-lg border">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>Title</TableHead>
						<TableHead>Status</TableHead>
						<TableHead>Source</TableHead>
						<TableHead>Category</TableHead>
						<TableHead>Created</TableHead>
						<TableHead className="text-right">Actions</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{ideas.map((idea) => (
						<TableRow key={idea._id}>
							<TableCell className="font-medium">
								{idea.title || "Untitled"}
							</TableCell>
							<TableCell>
								<StatusBadge status={idea.status} />
							</TableCell>
							<TableCell className="text-muted-foreground">
								{idea.source || "\u2014"}
							</TableCell>
							<TableCell className="text-muted-foreground">
								{idea.category || "\u2014"}
							</TableCell>
							<TableCell className="text-muted-foreground">
								{formatDate(idea._createdAt)}
							</TableCell>
							<TableCell className="text-right">
								{idea.status === "new" && (
									<div className="flex justify-end gap-2">
										<form action={approveIdea.bind(null, idea._id)}>
											<Button size="sm" variant="outline" className="text-green-600 hover:text-green-700">
												Approve
											</Button>
										</form>
										<form action={rejectIdea.bind(null, idea._id)}>
											<Button size="sm" variant="outline" className="text-red-600 hover:text-red-700">
												Reject
											</Button>
										</form>
									</div>
								)}
							</TableCell>
						</TableRow>
					))}
				</TableBody>
			</Table>
		</div>
	);
}
