import { defineField, defineType } from 'sanity';
import { HiOutlineVideoCamera } from 'react-icons/hi';

export default defineType({
  name: 'automatedVideo',
  title: 'Automated Video',
  type: 'document',
  icon: HiOutlineVideoCamera,
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contentIdea',
      title: 'Content Idea',
      type: 'reference',
      to: [{ type: 'contentIdea' }],
    }),
    defineField({
      name: 'script',
      title: 'Script',
      type: 'object',
      fields: [
        defineField({
          name: 'hook',
          title: 'Hook',
          type: 'text',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'scenes',
          title: 'Scenes',
          type: 'array',
          of: [
            {
              type: 'object',
              fields: [
                defineField({
                  name: 'sceneNumber',
                  title: 'Scene Number',
                  type: 'number',
                }),
                defineField({
                  name: 'narration',
                  title: 'Narration',
                  type: 'text',
                  validation: (Rule) => Rule.required(),
                }),
                defineField({
                  name: 'visualDescription',
                  title: 'Visual Description',
                  type: 'text',
                }),
                defineField({
                  name: 'bRollKeywords',
                  title: 'B-Roll Keywords',
                  type: 'array',
                  of: [{ type: 'string' }],
                }),
                defineField({
                  name: 'durationEstimate',
                  title: 'Duration Estimate',
                  type: 'number',
                }),
                defineField({
                  name: 'sceneType',
                  title: 'Scene Type',
                  type: 'string',
                  options: {
                    list: [
                      { title: 'Narration', value: 'narration' },
                      { title: 'Code', value: 'code' },
                      { title: 'List', value: 'list' },
                      { title: 'Comparison', value: 'comparison' },
                      { title: 'Mockup', value: 'mockup' },
                    ],
                  },
                  initialValue: 'narration',
                }),
                defineField({
                  name: 'imagePrompts',
                  title: 'Image Prompts',
                  type: 'array',
                  of: [{ type: 'string' }],
                  description: 'Per-scene infographic image generation prompts (generated by Gemini)',
                }),
                defineField({
                  name: 'code',
                  title: 'Code',
                  type: 'object',
                  hidden: ({ parent }) => parent?.sceneType !== 'code',
                  fields: [
                    defineField({
                      name: 'snippet',
                      title: 'Code Snippet',
                      type: 'text',
                    }),
                    defineField({
                      name: 'language',
                      title: 'Language',
                      type: 'string',
                      options: {
                        list: [
                          { title: 'TypeScript', value: 'typescript' },
                          { title: 'JavaScript', value: 'javascript' },
                          { title: 'JSX', value: 'jsx' },
                          { title: 'TSX', value: 'tsx' },
                          { title: 'CSS', value: 'css' },
                          { title: 'HTML', value: 'html' },
                          { title: 'JSON', value: 'json' },
                          { title: 'Bash', value: 'bash' },
                        ],
                      },
                    }),
                    defineField({
                      name: 'highlightLines',
                      title: 'Highlight Lines',
                      type: 'array',
                      of: [{ type: 'number' }],
                    }),
                  ],
                }),
                defineField({
                  name: 'list',
                  title: 'List',
                  type: 'object',
                  hidden: ({ parent }) => parent?.sceneType !== 'list',
                  fields: [
                    defineField({
                      name: 'items',
                      title: 'Items',
                      type: 'array',
                      of: [{ type: 'string' }],
                      validation: (Rule) => Rule.min(1),
                    }),
                    defineField({
                      name: 'icon',
                      title: 'Icon',
                      type: 'string',
                      description: 'Optional emoji icon, e.g. 🚀',
                    }),
                  ],
                }),
                defineField({
                  name: 'comparison',
                  title: 'Comparison',
                  type: 'object',
                  hidden: ({ parent }) => parent?.sceneType !== 'comparison',
                  fields: [
                    defineField({
                      name: 'leftLabel',
                      title: 'Left Label',
                      type: 'string',
                    }),
                    defineField({
                      name: 'rightLabel',
                      title: 'Right Label',
                      type: 'string',
                    }),
                    defineField({
                      name: 'rows',
                      title: 'Rows',
                      type: 'array',
                      of: [
                        {
                          type: 'object',
                          fields: [
                            defineField({ name: 'left', title: 'Left', type: 'string' }),
                            defineField({ name: 'right', title: 'Right', type: 'string' }),
                          ],
                        },
                      ],
                    }),
                  ],
                }),
                defineField({
                  name: 'mockup',
                  title: 'Mockup',
                  type: 'object',
                  hidden: ({ parent }) => parent?.sceneType !== 'mockup',
                  fields: [
                    defineField({
                      name: 'deviceType',
                      title: 'Device Type',
                      type: 'string',
                      options: {
                        list: [
                          { title: 'Browser', value: 'browser' },
                          { title: 'Phone', value: 'phone' },
                          { title: 'Terminal', value: 'terminal' },
                        ],
                      },
                    }),
                    defineField({
                      name: 'screenContent',
                      title: 'Screen Content',
                      type: 'text',
                      description: 'Description of what appears on screen',
                    }),
                  ],
                }),
              ],
            },
          ],
        }),
        defineField({
          name: 'cta',
          title: 'Call to Action',
          type: 'text',
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    defineField({
      name: 'scriptQualityScore',
      title: 'Script Quality Score',
      type: 'number',
    }),
    defineField({
      name: 'status',
      title: 'Pipeline Status',
      type: 'string',
      description: 'Read-only pipeline status — written by Cloudflare Workflow',
      options: {
        list: [
          { title: '1 - Draft', value: 'draft' },
          { title: '2 - Researching', value: 'researching' },
          { title: '3 - Research Complete', value: 'research_complete' },
          { title: '4 - Generating Media', value: 'generating_media' },
          { title: '5 - Generating Audio', value: 'generating_audio' },
          { title: '6 - Assembling Video', value: 'assembling_video' },
          { title: '7 - Quality Gate', value: 'quality_gate' },
          { title: '8 - Pending Review', value: 'pending_review' },
          { title: '9 - Approved', value: 'approved' },
          { title: '10 - Publishing', value: 'publishing' },
          { title: '11 - Published', value: 'published' },
          { title: 'Rejected', value: 'rejected' },
          { title: 'Archived', value: 'archived' },
          // Legacy v1 statuses — kept for existing documents. Remove in Task 1F.
          { title: 'Legacy: Script Ready', value: 'script_ready' },
          { title: 'Legacy: Audio Gen', value: 'audio_gen' },
          { title: 'Legacy: Video Gen', value: 'video_gen' },
          { title: 'Legacy: Rendering', value: 'rendering' },
          { title: 'Legacy: Uploading', value: 'uploading' },
          { title: 'Legacy: Flagged', value: 'flagged' },
          { title: 'Legacy: Infographics Generating', value: 'infographics_generating' },
          { title: 'Legacy: Enriching', value: 'enriching' },
        ],
      },
      initialValue: 'draft',
      validation: (Rule) => Rule.required(),
    }),

    // ─── v2: Quality Gate ────────────────────────────────────────────────
    defineField({
      name: 'qualityScore',
      title: 'Quality Score',
      type: 'number',
      description: 'AI critic quality score',
      hidden: true,
      validation: (rule) => rule.min(0).max(100),
    }),
    defineField({
      name: 'qualityIssues',
      title: 'Quality Issues',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Issues found by quality gate',
      hidden: true,
    }),

    // ─── v2: Review ──────────────────────────────────────────────────────
    defineField({
      name: 'reviewedAt',
      title: 'Reviewed At',
      type: 'datetime',
      description: 'When this video was reviewed',
      hidden: true,
    }),
    defineField({
      name: 'reviewedBy',
      title: 'Reviewed By',
      type: 'string',
      description: 'Who reviewed this video',
      hidden: true,
    }),

    // ─── v2: Media Assets ────────────────────────────────────────────────
    defineField({
      name: 'mediaAssets',
      title: 'Media Assets',
      type: 'array',
      description: 'Shared media: logos, screenshots, search images',
      of: [
        {
          type: 'reference',
          to: [{ type: 'mediaAsset' }],
        },
      ],
    }),

    // ─── v2: Shorts ──────────────────────────────────────────────────────
    defineField({
      name: 'shorts',
      title: 'Shorts',
      type: 'array',
      description: 'Short-form clips derived from this video',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
            }),
            defineField({
              name: 'startScene',
              title: 'Start Scene',
              type: 'number',
            }),
            defineField({
              name: 'endScene',
              title: 'End Scene',
              type: 'number',
            }),
            defineField({
              name: 'videoUrl',
              title: 'Video URL',
              type: 'string',
              description: 'URL to the rendered short video',
            }),
            defineField({
              name: 'thumbnailUrl',
              title: 'Thumbnail URL',
              type: 'string',
              description: 'URL to the short thumbnail',
            }),
          ],
        },
      ],
    }),

    // ─── v2: Thumbnails ──────────────────────────────────────────────────
    defineField({
      name: 'thumbnailHorizontal',
      title: 'Thumbnail (Horizontal 16:9)',
      type: 'image',
      options: { hotspot: true },
      description: 'Custom thumbnail for YouTube and landscape formats',
    }),
    defineField({
      name: 'thumbnailVertical',
      title: 'Thumbnail (Vertical 9:16)',
      type: 'image',
      options: { hotspot: true },
      description: 'Custom thumbnail for Shorts, Reels, and TikTok',
    }),

    // ─── v2: Blog Cross-Reference ────────────────────────────────────────
    defineField({
      name: 'blogPostId',
      title: 'Blog Post ID',
      type: 'string',
      description: 'Reference to generated blog post',
      hidden: true,
    }),

    // ─── v2: Social Posts ────────────────────────────────────────────────
    defineField({
      name: 'socialPosts',
      title: 'Social Posts',
      type: 'array',
      description: 'Tracking data for social media posts',
      hidden: true,
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'platform',
              title: 'Platform',
              type: 'string',
              options: {
                list: [
                  { title: 'YouTube', value: 'youtube' },
                  { title: 'Twitter/X', value: 'twitter' },
                  { title: 'LinkedIn', value: 'linkedin' },
                  { title: 'TikTok', value: 'tiktok' },
                  { title: 'Instagram', value: 'instagram' },
                  { title: 'Bluesky', value: 'bluesky' },
                ],
              },
            }),
            defineField({
              name: 'postId',
              title: 'Post ID',
              type: 'string',
            }),
            defineField({
              name: 'postUrl',
              title: 'Post URL',
              type: 'string',
              description: 'URL to the social media post',
            }),
            defineField({
              name: 'postedAt',
              title: 'Posted At',
              type: 'datetime',
            }),
          ],
        },
      ],
    }),

    // ─── v2: Workflow Tracking ───────────────────────────────────────────
    defineField({
      name: 'workflowId',
      title: 'Workflow ID',
      type: 'string',
      description: 'Cloudflare Workflow instance ID',
      hidden: true,
    }),
    defineField({
      name: 'r2Prefix',
      title: 'R2 Prefix',
      type: 'string',
      description: "R2 storage prefix for this video's assets",
      hidden: true,
    }),

    // ─── Existing Fields (backward compat) ───────────────────────────────
    defineField({
      name: 'audioFile',
      title: 'Audio File',
      type: 'file',
      description: 'ElevenLabs TTS audio (MP3) — generated in audio step',
      options: {
        accept: 'audio/*',
      },
    }),
    defineField({
      name: 'audioUrl',
      title: 'Audio URL',
      type: 'string', // string not url — R2/CDN paths may include query params that Sanity url validator rejects
      description: 'Direct URL to the audio file (auto-populated from audio asset)',
    }),
    defineField({
      name: 'videoFile',
      title: 'Video File (16:9)',
      type: 'file',
      description: 'Rendered main video (MP4)',
      options: {
        accept: 'video/*',
      },
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video URL',
      type: 'string', // string not url — R2/CDN paths may include query params
      description: 'Direct URL to the main video (auto-populated from video asset)',
    }),
    defineField({
      name: 'shortFile',
      title: 'Short Video File (9:16)',
      type: 'file',
      description: 'Rendered short video (MP4)',
      options: {
        accept: 'video/*',
      },
    }),
    defineField({
      name: 'shortUrl',
      title: 'Short URL',
      type: 'string', // string not url — R2/CDN paths may include query params
      description: 'Direct URL to the short video (auto-populated from video asset)',
    }),
    defineField({
      name: 'infographics',
      title: 'Infographics',
      type: 'array',
      description: 'Research infographics — reusable for blog posts and video b-roll',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            defineField({
              name: 'alt',
              title: 'Alt Text',
              type: 'string',
              description: 'Describe the infographic for accessibility',
            }),
            defineField({
              name: 'caption',
              title: 'Caption',
              type: 'string',
              description: 'Optional caption for display',
            }),
          ],
        },
      ],
    }),
    defineField({
      name: 'infographicsHorizontal',
      title: 'Infographics (Horizontal 16:9)',
      type: 'array',
      description: 'Generated infographic images for the horizontal/landscape video format',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'image',
              title: 'Image',
              type: 'image',
              options: { hotspot: true },
            }),
            defineField({
              name: 'prompt',
              title: 'Prompt',
              type: 'string',
              description: 'The image generation prompt used to create this infographic',
            }),
            defineField({
              name: 'sceneNumber',
              title: 'Scene Number',
              type: 'number',
              description: 'Which scene this infographic belongs to',
            }),
          ],
        },
      ],
    }),
    defineField({
      name: 'infographicsVertical',
      title: 'Infographics (Vertical 9:16)',
      type: 'array',
      description: 'Generated infographic images for the vertical/shorts video format',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'image',
              title: 'Image',
              type: 'image',
              options: { hotspot: true },
            }),
            defineField({
              name: 'prompt',
              title: 'Prompt',
              type: 'string',
              description: 'The image generation prompt used to create this infographic',
            }),
            defineField({
              name: 'sceneNumber',
              title: 'Scene Number',
              type: 'number',
              description: 'Which scene this infographic belongs to',
            }),
          ],
        },
      ],
    }),
    defineField({
      name: 'renderData',
      title: 'Render Data',
      type: 'object',
      description: 'Legacy: Remotion Lambda render tracking',
      fields: [
        defineField({ name: 'mainRenderId', title: 'Main Render ID', type: 'string' }),
        defineField({ name: 'shortRenderId', title: 'Short Render ID', type: 'string' }),
        defineField({ name: 'bucketName', title: 'Bucket Name', type: 'string' }),
        defineField({ name: 'startedAt', title: 'Started At', type: 'datetime' }),
      ],
      hidden: true,
    }),
    defineField({
      name: 'youtubeId',
      title: 'YouTube ID',
      type: 'string',
    }),
    defineField({
      name: 'youtubeShortId',
      title: 'YouTube Short ID',
      type: 'string',
    }),
    defineField({
      name: 'scheduledPublishAt',
      title: 'Scheduled Publish At',
      type: 'datetime',
    }),
    defineField({
      name: 'sponsorSlot',
      title: 'Sponsor Slot',
      type: 'reference',
      to: [{ type: 'sponsorLead' }],
    }),
    defineField({
      name: 'researchNotebookId',
      title: 'NotebookLM Notebook ID',
      type: 'string',
      description: 'Legacy: UUID of the NotebookLM notebook used for research',
      hidden: true,
    }),
    defineField({
      name: 'researchTaskId',
      title: 'Research Task ID',
      type: 'string',
      description: 'Legacy: UUID of the NotebookLM deep research task',
      hidden: true,
    }),
    defineField({
      name: 'researchInteractionId',
      title: 'Research Interaction ID',
      type: 'string',
      description: 'Gemini Deep Research interaction ID for polling via the Interactions API',
      hidden: true,
    }),
    defineField({
      name: 'researchData',
      title: 'Research Data',
      type: 'text',
      description: 'JSON-serialized research payload',
      hidden: true,
    }),
    defineField({
      name: 'infographicArtifactIds',
      title: 'Infographic Artifact IDs',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Legacy: NotebookLM artifact IDs for generated infographics',
      hidden: true,
    }),
    defineField({
      name: 'trendScore',
      title: 'Trend Score',
      type: 'number',
      description: 'Score from trend discovery (0-100)',
    }),
    defineField({
      name: 'trendSources',
      title: 'Trend Sources',
      type: 'string',
      description: 'Comma-separated list of trend signal sources',
    }),
    defineField({
      name: 'flaggedReason',
      title: 'Flagged Reason',
      type: 'text',
    }),
    defineField({
      name: 'distributionLog',
      title: 'Distribution Log',
      type: 'array',
      description: 'Tracks distribution step results for retry and debugging',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'step', title: 'Step', type: 'string' }),
            defineField({
              name: 'status',
              title: 'Status',
              type: 'string',
              options: { list: ['success', 'failed', 'skipped'] },
            }),
            defineField({ name: 'error', title: 'Error', type: 'text' }),
            defineField({ name: 'timestamp', title: 'Timestamp', type: 'datetime' }),
            defineField({
              name: 'result',
              title: 'Result',
              type: 'string',
              description: 'e.g. YouTube video ID, tweet ID',
            }),
          ],
        },
      ],
      hidden: true,
    }),
  ],
  orderings: [
    {
      title: 'Status',
      name: 'statusAsc',
      by: [{ field: 'status', direction: 'asc' }],
    },
    {
      title: 'Scheduled Publish Date',
      name: 'scheduledPublishAtDesc',
      by: [{ field: 'scheduledPublishAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'status',
    },
  },
});
