projects:
  ccd:
    schemaPath: nextjs/src/graphql/schema.json
    includes:
      - nextjs/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ""
        docsFilePath: nextjs/src/graphql
extensions:
  amplify:
    version: 3
