projects:
  ccd:
    schemaPath: amplify/backend/api/ccd/build/schema.graphql
    includes:
      - nextjs/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: nextjs/src/graphql
extensions:
  amplify:
    version: 3
