packages:
  - "apps/*"

overrides:
  "@portabletext/sanity-bridge": "^1.2.14"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

peerDependencyRules:
  allowAny:
    - react
    - react-dom
