packages:
  - "apps/*"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
  - "@tailwindcss/oxide"
patchedDependencies:
  workers-ai-provider: patches/workers-ai-provider.patch

peerDependencyRules:
  allowAny:
    - react
    - react-dom
