/**
 * Remotion Lambda rendering service.
 *
 * Handles deploying and triggering Remotion Lambda renders for video production.
 * Produces both 16:9 (main) and 9:16 (short) video formats.
 *
 * Requires env vars:
 * - AWS_ACCESS_KEY_ID
 * - AWS_SECRET_ACCESS_KEY
 * - REMOTION_AWS_REGION
 * - REMOTION_SERVE_URL (generated during Lambda deployment)
 * - REMOTION_FUNCTION_NAME (optional, from deployRemotionLambda)
 *
 * @module lib/services/remotion
 */

import {
  renderMediaOnLambda,
  getRenderProgress,
  deploySite,
  deployFunction,
  getOrCreateBucket,
  type AwsRegion,
  type RenderMediaOnLambdaInput,
  type RenderProgress,
} from "@remotion/lambda";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RemotionConfig {
  awsAccessKeyId: string;
  awsSecretAccessKey: string;
  region: string;
  serveUrl: string;
}

export interface RenderInput {
  /** URL to the TTS audio file */
  audioUrl: string;
  /** Video script data */
  script: {
    hook: string;
    scenes: Array<{
      narration: string;
      keywords?: string[];
      visualDescription?: string;
      bRollKeywords?: string[];
      sceneNumber?: number;
      durationEstimate?: number;
    }>;
    cta: string;
  };
  /** B-roll video URLs mapped by scene index */
  bRollUrls: Record<number, string>;
  /** Optional sponsor data */
  sponsor?: {
    name: string;
    logoUrl?: string;
    message?: string;
  };
  /** Audio duration in seconds */
  audioDurationSeconds: number;
}

export interface RenderResult {
  /** URL to the rendered video file */
  videoUrl: string;
  /** Render duration in seconds */
  renderDurationSeconds: number;
  /** Output file size in bytes */
  fileSizeBytes: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default Lambda function name if REMOTION_FUNCTION_NAME is not set */
const DEFAULT_FUNCTION_NAME = "remotion-render-4-0-431";

/** Polling interval in ms when waiting for render completion */
const POLL_INTERVAL_MS = 2_000;

/** Maximum time to wait for a render before timing out (15 minutes) */
const RENDER_TIMEOUT_MS = 15 * 60 * 1_000;

/** Progress thresholds at which we log milestones (0–1) */
const LOG_MILESTONES = [0.1, 0.25, 0.5, 0.75, 0.9, 1.0];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log(message: string, data?: Record<string, unknown>): void {
  const ts = new Date().toISOString();
  if (data) {
    console.log(`[REMOTION] [${ts}] ${message}`, data);
  } else {
    console.log(`[REMOTION] [${ts}] ${message}`);
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Map a RenderInput into the inputProps shape expected by the Remotion composition.
 */
function mapInputProps(input: RenderInput): Record<string, unknown> {
  return {
    audioUrl: input.audioUrl,
    audioDurationInSeconds: input.audioDurationSeconds,
    hook: input.script.hook,
    scenes: input.script.scenes.map((s, i) => ({
      narration: s.narration,
      visualDescription: s.visualDescription,
      bRollKeywords: s.bRollKeywords,
      sceneNumber: s.sceneNumber,
      durationEstimate: s.durationEstimate,
      bRollUrl: input.bRollUrls[i],
    })),
    cta: input.script.cta,
    sponsor: input.sponsor,
  };
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/**
 * Get Remotion Lambda configuration from environment variables.
 * Throws if any required env var is missing.
 */
export function getRemotionConfig(): RemotionConfig {
  const awsAccessKeyId = process.env.AWS_ACCESS_KEY_ID;
  const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  const region = process.env.REMOTION_AWS_REGION;
  const serveUrl = process.env.REMOTION_SERVE_URL;

  const missing: string[] = [];
  if (!awsAccessKeyId) missing.push("AWS_ACCESS_KEY_ID");
  if (!awsSecretAccessKey) missing.push("AWS_SECRET_ACCESS_KEY");
  if (!region) missing.push("REMOTION_AWS_REGION");
  if (!serveUrl) missing.push("REMOTION_SERVE_URL");

  if (missing.length > 0) {
    throw new Error(
      `[REMOTION] Missing required environment variables: ${missing.join(", ")}. ` +
        `Set these before calling any render function. ` +
        `REMOTION_SERVE_URL is generated by running deployRemotionLambda().`
    );
  }

  return {
    awsAccessKeyId: awsAccessKeyId!,
    awsSecretAccessKey: awsSecretAccessKey!,
    region: region!,
    serveUrl: serveUrl!,
  };
}

/**
 * Get the Lambda function name from env or use the default.
 */
function getFunctionName(): string {
  return process.env.REMOTION_FUNCTION_NAME || DEFAULT_FUNCTION_NAME;
}

// ---------------------------------------------------------------------------
// Core render + poll
// ---------------------------------------------------------------------------

/**
 * Trigger a render on Lambda and poll until completion.
 *
 * @param composition - The Remotion composition ID ("MainVideo" or "ShortVideo")
 * @param input       - The render input data
 * @returns           - The render result with video URL and metadata
 */
async function triggerAndPollRender(
  composition: string,
  input: RenderInput
): Promise<RenderResult> {
  const config = getRemotionConfig();
  const functionName = getFunctionName();
  const region = config.region as AwsRegion;
  const startTime = Date.now();

  log(`Starting render for composition "${composition}"`, {
    scenes: input.script.scenes.length,
    audioDuration: input.audioDurationSeconds,
    functionName,
    region,
  });

  // ---- 1. Trigger the render ----
  let renderId: string;
  let bucketName: string;

  try {
    const renderResponse = await renderMediaOnLambda({
      composition,
      serveUrl: config.serveUrl,
      codec: "h264",
      inputProps: mapInputProps(input),
      region,
      functionName,
      // Remotion reads AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY from env
      // automatically, but we can also pass them explicitly if needed.
    });

    renderId = renderResponse.renderId;
    bucketName = renderResponse.bucketName;

    log(`Render triggered successfully`, {
      renderId,
      bucketName,
      composition,
    });
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : String(err);
    throw new Error(
      `[REMOTION] Failed to trigger Lambda render for "${composition}": ${message}. ` +
        `Ensure the Lambda function "${functionName}" is deployed in ${region} ` +
        `and REMOTION_SERVE_URL points to a valid Remotion bundle.`
    );
  }

  // ---- 2. Poll for completion ----
  let lastLoggedMilestone = -1;

  while (true) {
    const elapsed = Date.now() - startTime;

    if (elapsed > RENDER_TIMEOUT_MS) {
      throw new Error(
        `[REMOTION] Render timed out after ${Math.round(elapsed / 1000)}s ` +
          `for composition "${composition}" (renderId: ${renderId}). ` +
          `Max timeout is ${RENDER_TIMEOUT_MS / 1000}s.`
      );
    }

    await sleep(POLL_INTERVAL_MS);

    let progress: RenderProgress;
    try {
      progress = await getRenderProgress({
        renderId,
        bucketName,
        region,
        functionName,
      });
    } catch (err: unknown) {
      const message =
        err instanceof Error ? err.message : String(err);
      log(`Warning: Failed to fetch render progress (will retry): ${message}`);
      continue;
    }

    // Log milestone progress
    const overallProgress = progress.overallProgress ?? 0;
    for (const milestone of LOG_MILESTONES) {
      if (
        overallProgress >= milestone &&
        milestone > lastLoggedMilestone
      ) {
        log(
          `Render progress: ${Math.round(overallProgress * 100)}% ` +
            `(composition: ${composition}, renderId: ${renderId})`
        );
        lastLoggedMilestone = milestone;
        break;
      }
    }

    // Check for fatal errors
    if (progress.fatalErrorEncountered) {
      const errorMessages = (progress.errors ?? [])
        .map((e) => {
          if (typeof e === "string") return e;
          if (e && typeof e === "object" && "message" in e)
            return (e as { message: string }).message;
          return JSON.stringify(e);
        })
        .join("; ");

      throw new Error(
        `[REMOTION] Render failed for "${composition}" (renderId: ${renderId}): ` +
          `${errorMessages || "Unknown fatal error"}. ` +
          `Check CloudWatch logs for function "${functionName}" in ${region}.`
      );
    }

    // Check for completion
    if (progress.done) {
      const elapsedSeconds = (Date.now() - startTime) / 1000;
      const outputUrl = progress.outputFile ?? "";
      const outputSize = progress.outputSizeInBytes ?? 0;

      if (!outputUrl) {
        throw new Error(
          `[REMOTION] Render completed but no output URL returned ` +
            `for "${composition}" (renderId: ${renderId}). ` +
            `This may indicate a configuration issue with the S3 bucket.`
        );
      }

      log(`Render complete for "${composition}"`, {
        renderId,
        durationSeconds: Math.round(elapsedSeconds * 10) / 10,
        fileSizeBytes: outputSize,
        outputUrl,
      });

      return {
        videoUrl: outputUrl,
        renderDurationSeconds: Math.round(elapsedSeconds * 10) / 10,
        fileSizeBytes: outputSize,
      };
    }
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Render the main 16:9 landscape video using Remotion Lambda.
 *
 * @param input - Render input data (audio, script, B-roll, sponsor)
 * @returns Render result with video URL
 */
export async function renderMainVideo(
  input: RenderInput
): Promise<RenderResult> {
  log(
    `renderMainVideo called with ${input.script.scenes.length} scenes, ` +
      `${input.audioDurationSeconds}s audio`
  );
  return triggerAndPollRender("MainVideo", input);
}

/**
 * Render the 9:16 portrait Short video using Remotion Lambda.
 *
 * @param input - Render input data (audio, script, B-roll, sponsor)
 * @returns Render result with video URL
 */
export async function renderShortVideo(
  input: RenderInput
): Promise<RenderResult> {
  log(
    `renderShortVideo called with ${input.script.scenes.length} scenes, ` +
      `${input.audioDurationSeconds}s audio`
  );
  return triggerAndPollRender("ShortVideo", input);
}

/**
 * Render both video formats (main + short) in parallel.
 *
 * @param input - Render input data
 * @returns Object with both render results
 */
export async function renderBothFormats(
  input: RenderInput
): Promise<{ main: RenderResult; short: RenderResult }> {
  log(
    `Starting parallel render of MainVideo + ShortVideo ` +
      `(${input.script.scenes.length} scenes, ${input.audioDurationSeconds}s audio)`
  );

  const [main, short] = await Promise.all([
    renderMainVideo(input),
    renderShortVideo(input),
  ]);

  log(
    `Both renders complete. Main: ${main.fileSizeBytes} bytes (${main.renderDurationSeconds}s), ` +
      `Short: ${short.fileSizeBytes} bytes (${short.renderDurationSeconds}s)`
  );

  return { main, short };
}

// ---------------------------------------------------------------------------
// Deploy helper (one-time setup)
// ---------------------------------------------------------------------------

export interface DeployResult {
  functionName: string;
  serveUrl: string;
  siteName: string;
  bucketName: string;
  region: string;
}

/**
 * Deploy the Remotion Lambda infrastructure (one-time setup).
 *
 * This will:
 * 1. Create or reuse an S3 bucket for Remotion
 * 2. Deploy the Remotion bundle (site) to S3
 * 3. Deploy the Lambda function
 *
 * After running this, set the returned `serveUrl` as REMOTION_SERVE_URL
 * and `functionName` as REMOTION_FUNCTION_NAME in your environment.
 *
 * @param entryPoint - Path to the Remotion entry file (e.g., "remotion/index.ts")
 * @returns Deploy result with function name, serve URL, etc.
 */
export async function deployRemotionLambda(
  entryPoint: string = "remotion/index.ts"
): Promise<DeployResult> {
  const region = (process.env.REMOTION_AWS_REGION || "us-east-1") as AwsRegion;

  if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY) {
    throw new Error(
      "[REMOTION] Cannot deploy: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY " +
        "must be set in environment variables."
    );
  }

  log("Starting Remotion Lambda deployment", { region, entryPoint });

  // Step 1: Get or create the S3 bucket
  log("Step 1/3: Getting or creating S3 bucket...");
  let bucketName: string;
  try {
    const bucketResult = await getOrCreateBucket({ region });
    bucketName = bucketResult.bucketName;
    log(`Bucket ready: ${bucketName}`);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `[REMOTION] Failed to get or create S3 bucket in ${region}: ${message}. ` +
        `Ensure your AWS credentials have S3 permissions.`
    );
  }

  // Step 2: Deploy the site (bundle) to S3
  log("Step 2/3: Deploying Remotion bundle to S3...");
  let serveUrl: string;
  let siteName: string;
  try {
    const siteResult = await deploySite({
      entryPoint,
      bucketName,
      region,
      siteName: "codingcat-video-pipeline",
      options: {
        onBundleProgress: (progress: number) => {
          if (progress % 25 === 0 || progress === 100) {
            log(`Bundle progress: ${progress}%`);
          }
        },
        onUploadProgress: (upload) => {
          if (upload.totalFiles > 0) {
            const pct = Math.round(
              (upload.filesUploaded / upload.totalFiles) * 100
            );
            if (pct % 25 === 0) {
              log(
                `Upload progress: ${upload.filesUploaded}/${upload.totalFiles} files (${pct}%)`
              );
            }
          }
        },
      },
    });
    serveUrl = siteResult.serveUrl;
    siteName = siteResult.siteName;
    log(`Site deployed: ${serveUrl}`, { siteName });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `[REMOTION] Failed to deploy site to S3: ${message}. ` +
        `Ensure the entry point "${entryPoint}" exists and is a valid Remotion project.`
    );
  }

  // Step 3: Deploy the Lambda function
  log("Step 3/3: Deploying Lambda function...");
  let functionName: string;
  try {
    const fnResult = await deployFunction({
      region,
      timeoutInSeconds: 240,
      memorySizeInMb: 2048,
      createCloudWatchLogGroup: true,
      cloudWatchLogRetentionPeriodInDays: 14,
      diskSizeInMb: 2048,
    });
    functionName = fnResult.functionName;
    log(
      `Lambda function deployed: ${functionName}` +
        (fnResult.alreadyExisted ? " (already existed)" : " (newly created)")
    );
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `[REMOTION] Failed to deploy Lambda function: ${message}. ` +
        `Ensure your AWS credentials have Lambda and IAM permissions. ` +
        `See: https://www.remotion.dev/docs/lambda/permissions`
    );
  }

  log("Deployment complete! Set these environment variables:", {
    REMOTION_SERVE_URL: serveUrl,
    REMOTION_FUNCTION_NAME: functionName,
    REMOTION_AWS_REGION: region,
  });

  return {
    functionName,
    serveUrl,
    siteName,
    bucketName,
    region,
  };
}
