/**
 * Remotion Lambda rendering service â runtime only.
 *
 * Handles triggering and polling Remotion Lambda renders for video production.
 * Produces both 16:9 (main) and 9:16 (short) video formats.
 *
 * Deploy functions (deploySite, deployFunction, getOrCreateBucket) live in
 * `remotion-deploy.ts` to avoid pulling @rspack/binding into Vercel bundles.
 *
 * Requires env vars:
 * - AWS_ACCESS_KEY_ID
 * - AWS_SECRET_ACCESS_KEY
 * - REMOTION_AWS_REGION
 * - REMOTION_SERVE_URL (generated during Lambda deployment)
 * - REMOTION_FUNCTION_NAME (optional, defaults to DEFAULT_FUNCTION_NAME)
 *
 * @module lib/services/remotion
 */

import {
  renderMediaOnLambda,
  getRenderProgress,
  type AwsRegion,
} from "@remotion/lambda/client";
import { getConfigValue } from "@/lib/config";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RemotionLambdaConfig {
  awsAccessKeyId: string;
  awsSecretAccessKey: string;
  region: string;
  serveUrl: string;
}

export interface RenderInput {
  /** URL to the TTS audio file */
  audioUrl: string;
  /** Video script data */
  script: {
    hook: string;
    scenes: Array<{
      narration: string;
      keywords?: string[];
      visualDescription?: string;
      bRollKeywords?: string[];
      sceneNumber?: number;
      durationEstimate?: number;
    }>;
    cta: string;
  };
  /** B-roll video URLs mapped by scene index */
  bRollUrls: Record<number, string>;
  /** Optional sponsor data */
  sponsor?: {
    name: string;
    logoUrl?: string;
    message?: string;
  };
  /** Audio duration in seconds */
  audioDurationSeconds: number;
}

export interface RenderResult {
  /** URL to the rendered video file */
  videoUrl: string;
  /** Render duration in seconds */
  renderDurationSeconds: number;
  /** Output file size in bytes */
  fileSizeBytes: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Default Lambda function name if REMOTION_FUNCTION_NAME is not set */
const DEFAULT_FUNCTION_NAME = "remotion-render-4-0-431";

/** Polling interval in ms when waiting for render completion */
const POLL_INTERVAL_MS = 2_000;

/** Maximum time to wait for a render before timing out (15 minutes) */
const RENDER_TIMEOUT_MS = 15 * 60 * 1_000;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log(message: string, data?: Record<string, unknown>): void {
  const ts = new Date().toISOString();
  if (data) {
    console.log(`[REMOTION] [${ts}] ${message}`, data);
  } else {
    console.log(`[REMOTION] [${ts}] ${message}`);
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Map a RenderInput into the inputProps shape expected by the Remotion composition.
 */
function mapInputProps(input: RenderInput): Record<string, unknown> {
  return {
    audioUrl: input.audioUrl,
    audioDurationInSeconds: input.audioDurationSeconds,
    hook: input.script.hook,
    scenes: input.script.scenes.map((s, i) => ({
      narration: s.narration,
      visualDescription: s.visualDescription,
      bRollKeywords: s.bRollKeywords,
      sceneNumber: s.sceneNumber,
      durationEstimate: s.durationEstimate,
      bRollUrl: input.bRollUrls[i],
    })),
    cta: input.script.cta,
    sponsor: input.sponsor,
  };
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/**
 * Get Remotion Lambda configuration from environment variables.
 * Throws if any required env var is missing.
 */
export async function getRemotionConfig(): Promise<RemotionLambdaConfig> {
  const awsAccessKeyId = process.env.AWS_ACCESS_KEY_ID;
  const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  const region = await getConfigValue("remotion_config", "awsRegion", process.env.REMOTION_AWS_REGION);
  const serveUrl = await getConfigValue("remotion_config", "serveUrl", process.env.REMOTION_SERVE_URL);

  const missing: string[] = [];
  if (!awsAccessKeyId) missing.push("AWS_ACCESS_KEY_ID");
  if (!awsSecretAccessKey) missing.push("AWS_SECRET_ACCESS_KEY");
  if (!region) missing.push("REMOTION_AWS_REGION");
  if (!serveUrl) missing.push("REMOTION_SERVE_URL");

  if (missing.length > 0) {
    throw new Error(
      `[REMOTION] Missing required environment variables: ${missing.join(", ")}. ` +
        `Set these before calling any render function. ` +
        `REMOTION_SERVE_URL is generated by running deployRemotionLambda().`
    );
  }

  return {
    awsAccessKeyId: awsAccessKeyId!,
    awsSecretAccessKey: awsSecretAccessKey!,
    region: region!,
    serveUrl: serveUrl!,
  };
}

/**
 * Get the Lambda function name from env or use the default.
 */
async function getFunctionName(): Promise<string> {
  return getConfigValue("remotion_config", "functionName", process.env.REMOTION_FUNCTION_NAME || DEFAULT_FUNCTION_NAME);
}

// ---------------------------------------------------------------------------
// Types â render start (no polling)
// ---------------------------------------------------------------------------

export interface RenderStartResult {
  mainRenderId: string;
  shortRenderId: string;
  bucketName: string;
}

export interface RenderProgressResult {
  done: boolean;
  /** 0-100 */
  progress: number;
  outputUrl?: string;
  outputSize?: number;
  errors?: string;
}

export interface BothRendersResult {
  allDone: boolean;
  main: RenderProgressResult;
  short: RenderProgressResult;
}

// ---------------------------------------------------------------------------
// Core â start a single render (no polling)
// ---------------------------------------------------------------------------

/**
 * Trigger a render on Lambda and return immediately with the render ID.
 * Does NOT poll for completion.
 */
async function startRender(
  composition: string,
  input: RenderInput
): Promise<{ renderId: string; bucketName: string }> {
  const config = await getRemotionConfig();
  const functionName = await getFunctionName();
  const region = config.region as AwsRegion;

  log(`Starting render for composition "${composition}"`, {
    scenes: input.script.scenes.length,
    audioDuration: input.audioDurationSeconds,
    functionName,
    region,
  });

  try {
    const renderResponse = await renderMediaOnLambda({
      composition,
      serveUrl: config.serveUrl,
      codec: "h264",
      inputProps: mapInputProps(input),
      region,
      functionName,
    });

    log(`Render triggered successfully`, {
      renderId: renderResponse.renderId,
      bucketName: renderResponse.bucketName,
      composition,
    });

    return {
      renderId: renderResponse.renderId,
      bucketName: renderResponse.bucketName,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `[REMOTION] Failed to trigger Lambda render for "${composition}": ${message}. ` +
        `Ensure the Lambda function "${functionName}" is deployed in ${region} ` +
        `and REMOTION_SERVE_URL points to a valid Remotion bundle.`
    );
  }
}

// ---------------------------------------------------------------------------
// Public API â start renders
// ---------------------------------------------------------------------------

/**
 * Start 