/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d640f285-9cf8-4be6-bac8-d8f43b68470a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_p0bw5lOuR",
    "aws_user_pools_web_client_id": "4f3joni8s6205gq0c3fedlf90c",
    "oauth": {
        "domain": "ccd895ca1f4-895ca1f4-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://omyrvens2bfg3hqtsxky4wi4ua.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iyb5otnbrvej5emr5snugd3oku"
};


export default awsmobile;
