import { Timestamp } from 'firebase/firestore';
import { CoverMedia } from './post.model';
export interface Sponsor {
  //Auto Generated By Cloud Function
  _id: string;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
  createdBy?: string;
  updatedBy?: string;

  //Core Fields
  company: string;
  slug: string;
  coverPhoto?: CoverMedia;
  coverVideo?: CoverMedia;
  description?: string;
  url?: string;
}
