backend:
  name: git-gateway
  branch: dev
publish_mode: editorial_workflow
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "post"
    label: "post"
    folder: "src/content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}