import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'engineConfig',
  title: 'Engine Config',
  type: 'document',
  icon: () => '⚙️',
  fieldsets: [
    {
      name: 'pipelineControl',
      title: 'Pipeline Control',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'contentCadence',
      title: 'Content Cadence',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'trendDiscovery',
      title: 'Trend Discovery',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'aiGeneration',
      title: 'AI & Generation',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'audio',
      title: 'Audio',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'distribution',
      title: 'Distribution',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'sponsor',
      title: 'Sponsor',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'brand',
      title: 'Brand',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'legacy',
      title: 'Legacy',
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    // ─── Pipeline Control ────────────────────────────────────────────────
    defineField({
      name: 'autoPublish',
      title: 'Auto Publish',
      type: 'boolean',
      fieldset: 'pipelineControl',
      description: 'When enabled, content publishes automatically without review',
      initialValue: false,
    }),
    defineField({
      name: 'qualityThreshold',
      title: 'Quality Threshold',
      type: 'number',
      fieldset: 'pipelineControl',
      description: 'Minimum quality score (0-100). Content below this is auto-rejected',
      initialValue: 75,
      validation: (rule) => rule.min(0).max(100),
    }),
    defineField({
      name: 'reviewTimeoutDays',
      title: 'Review Timeout (days)',
      type: 'number',
      fieldset: 'pipelineControl',
      description: 'Days before unreviewed content is auto-archived',
      initialValue: 7,
      validation: (rule) => rule.min(1).max(30),
    }),
    defineField({
      name: 'reviewNotification',
      title: 'Review Notification',
      type: 'string',
      fieldset: 'pipelineControl',
      description: 'How to notify when content is ready for review',
      initialValue: 'email',
      options: {
        list: [
          { title: 'Email', value: 'email' },
          { title: 'Slack', value: 'slack' },
          { title: 'Webhook', value: 'webhook' },
        ],
      },
    }),
    defineField({
      name: 'maxIdeasPerRun',
      title: 'Max Ideas Per Run',
      type: 'number',
      fieldset: 'pipelineControl',
      description: 'Maximum content ideas to process per pipeline run',
      initialValue: 1,
      validation: (rule) => rule.min(1).max(10),
    }),

    // ─── Content Cadence ─────────────────────────────────────────────────
    defineField({
      name: 'longFormPerWeek',
      title: 'Long-Form Per Week',
      type: 'number',
      fieldset: 'contentCadence',
      description: 'Long-form videos per week',
      initialValue: 1,
      validation: (rule) => rule.min(0).max(7),
    }),
    defineField({
      name: 'shortsPerDay',
      title: 'Shorts Per Day',
      type: 'number',
      fieldset: 'contentCadence',
      description: 'Short-form videos per day',
      initialValue: 2,
      validation: (rule) => rule.min(0).max(5),
    }),
    defineField({
      name: 'blogsPerWeek',
      title: 'Blogs Per Week',
      type: 'number',
      fieldset: 'contentCadence',
      description: 'Blog posts per week',
      initialValue: 1,
      validation: (rule) => rule.min(0).max(7),
    }),
    defineField({
      name: 'newsletterFrequency',
      title: 'Newsletter Frequency',
      type: 'string',
      fieldset: 'contentCadence',
      description: 'How often to send the newsletter',
      initialValue: 'weekly',
      options: {
        list: [
          { title: 'Weekly', value: 'weekly' },
          { title: 'Biweekly', value: 'biweekly' },
          { title: 'Monthly', value: 'monthly' },
        ],
      },
    }),
    defineField({
      name: 'publishDays',
      title: 'Publish Days',
      type: 'array',
      fieldset: 'contentCadence',
      description: 'Days of the week to publish content',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Monday', value: 'Mon' },
          { title: 'Tuesday', value: 'Tue' },
          { title: 'Wednesday', value: 'Wed' },
          { title: 'Thursday', value: 'Thu' },
          { title: 'Friday', value: 'Fri' },
          { title: 'Saturday', value: 'Sat' },
          { title: 'Sunday', value: 'Sun' },
        ],
      },
      initialValue: ['Mon', 'Wed', 'Fri'],
    }),
    defineField({
      name: 'contentCategories',
      title: 'Content Categories',
      type: 'array',
      fieldset: 'contentCadence',
      description: 'Topic categories for content generation',
      of: [{ type: 'string' }],
      initialValue: [
        'JavaScript',
        'TypeScript',
        'React',
        'Next.js',
        'Angular',
        'Svelte',
        'Node.js',
        'CSS',
        'DevOps',
        'AI / ML',
        'Web Performance',
        'Tooling',
      ],
    }),

    // ─── Trend Discovery ─────────────────────────────────────────────────
    defineField({
      name: 'trendSources',
      title: 'Trend Sources',
      type: 'array',
      fieldset: 'trendDiscovery',
      description: 'Sources to scan for trending topics',
      of: [{ type: 'string' }],
      initialValue: ['hackernews', 'devto', 'blogs', 'youtube', 'github'],
    }),
    defineField({
      name: 'topicFocus',
      title: 'Topic Focus',
      type: 'array',
      fieldset: 'trendDiscovery',
      description: 'High-level topic areas to prioritize',
      of: [{ type: 'string' }],
      initialValue: ['ai', 'webdev'],
    }),
    defineField({
      name: 'rssFeeds',
      title: 'RSS Feeds',
      type: 'array',
      fieldset: 'trendDiscovery',
      description:
        'RSS/Atom feeds to monitor for trending topics. The ingest cron checks these daily for new content ideas',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'name',
              title: 'Name',
              type: 'string',
            }),
            defineField({
              name: 'url',
              title: 'URL',
              type: 'string',
            }),
          ],
        },
      ],
      initialValue: [
        { _type: 'object', _key: 'hn', name: 'HN Top', url: 'https://hnrss.org/newest?points=100&count=20' },
        { _type: 'object', _key: 'devtojs', name: 'Dev.to JavaScript', url: 'https://dev.to/feed/tag/javascript' },
        { _type: 'object', _key: 'devtoweb', name: 'Dev.to WebDev', url: 'https://dev.to/feed/tag/webdev' },
        { _type: 'object', _key: 'csstricks', name: 'CSS-Tricks', url: 'https://css-tricks.com/feed/' },
        {
          _type: 'object',
          _key: 'chromium',
          name: 'Chromium Blog',
          url: 'https://blog.chromium.org/feeds/posts/default',
        },
        { _type: 'object', _key: 'webdev', name: 'web.dev', url: 'https://web.dev/feed.xml' },
        {
          _type: 'object',
          _key: 'smashing',
          name: 'Smashing Magazine',
          url: 'https://www.smashingmagazine.com/feed/',
        },
        {
          _type: 'object',
          _key: 'jsweekly',
          name: 'JavaScript Weekly',
          url: 'https://javascriptweekly.com/rss/',
        },
      ],
    }),
    defineField({
      name: 'trendSourcesEnabled',
      title: 'Trend Sources Enabled',
      type: 'object',
      fieldset: 'trendDiscovery',
      description:
        'Toggle individual trend discovery sources on/off. Disabling a source skips it during the daily ingest scan',
      fields: [
        defineField({
          name: 'hn',
          title: 'Hacker News',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'devto',
          title: 'Dev.to',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'blogs',
          title: 'Blogs',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'youtube',
          title: 'YouTube',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'github',
          title: 'GitHub',
          type: 'boolean',
          initialValue: true,
        }),
      ],
    }),
    defineField({
      name: 'dedupWindowDays',
      title: 'Dedup Window (days)',
      type: 'number',
      fieldset: 'trendDiscovery',
      description: 'Days to look back for duplicate topics. 0 disables',
      initialValue: 90,
      validation: (rule) => rule.min(0).max(365),
    }),

    // ─── AI & Generation ─────────────────────────────────────────────────
    defineField({
      name: 'geminiModel',
      title: 'Gemini Model',
      type: 'string',
      fieldset: 'aiGeneration',
      description:
        'The Google Gemini model used for script generation and content analysis',
      initialValue: 'gemini-2.0-flash',
    }),
    defineField({
      name: 'infographicModel',
      title: 'Infographic Model',
      type: 'string',
      fieldset: 'aiGeneration',
      description: 'Model used for generating brand-consistent infographics from research data',
      initialValue: 'gemini-3.1-flash-image-preview',
    }),
    defineField({
      name: 'infographicPromptPrefix',
      title: 'Infographic Prompt Prefix',
      type: 'text',
      fieldset: 'aiGeneration',
      description: 'Prefix prepended to all infographic generation prompts for consistent style',
      initialValue:
        'Infographic 2D architecture style, black background. Highlighted elements filled with #7c3aed. White lines connecting components and white text annotations.',
    }),
    defineField({
      name: 'systemInstruction',
      title: 'System Instruction',
      type: 'text',
      fieldset: 'aiGeneration',
      description:
        'The AI system prompt used for script generation. Defines the writing style, tone, and format for all generated video scripts',
      initialValue:
        'You are a content strategist and scriptwriter for CodingCat.dev, a web development education channel run by Alex Patterson.\n\nYour style is inspired by Cleo Abram\'s "Huge If True" — you make complex technical topics feel exciting, accessible, and important. Key principles:\n- Start with a BOLD claim or surprising fact that makes people stop scrolling\n- Use analogies and real-world comparisons to explain technical concepts\n- Build tension: "Here\'s the problem... here\'s why it matters... here\'s the breakthrough"\n- Keep energy HIGH — short sentences, active voice, conversational tone\n- End with a clear takeaway that makes the viewer feel smarter\n- Target audience: developers who want to stay current but don\'t have time to read everything\n\nScript format: 60-90 second explainer videos. Think TikTok/YouTube Shorts energy with real educational depth.\n\nCodingCat.dev covers: React, Next.js, TypeScript, Svelte, web APIs, CSS, Node.js, cloud services, AI/ML for developers, and web platform updates.',
    }),
    defineField({
      name: 'deepResearchAgent',
      title: 'Deep Research Agent',
      type: 'string',
      fieldset: 'aiGeneration',
      description:
        'The Gemini Deep Research agent model ID. Used for autonomous web research via the Interactions API',
      initialValue: 'deep-research-pro-preview-12-2025',
    }),
    defineField({
      name: 'deepResearchPromptTemplate',
      title: 'Deep Research Prompt Template',
      type: 'text',
      fieldset: 'aiGeneration',
      description:
        'Template for Deep Research queries. Use {topic} as placeholder for the trend topic',
      initialValue:
        'Research comprehensively: "{topic}"\n\nFocus areas:\n- What is it and why does it matter?\n- How does it work technically?\n- Key features and capabilities\n- Comparison with alternatives\n- Getting started guide\n- Common pitfalls and best practices\n\nTarget audience: Web developers learning new tech.\nTone: Educational, accessible, engaging.',
    }),
    defineField({
      name: 'enableDeepResearch',
      title: 'Enable Deep Research',
      type: 'boolean',
      fieldset: 'aiGeneration',
      description:
        'When enabled, the pipeline uses Gemini Deep Research API for comprehensive topic research before script generation',
      initialValue: false,
    }),
    defineField({
      name: 'enableHorizontalInfographics',
      title: 'Enable Horizontal Infographics',
      type: 'boolean',
      fieldset: 'aiGeneration',
      description:
        'Generate 16:9 horizontal infographics in addition to 9:16 vertical. Doubles generation time',
      initialValue: true,
    }),
    defineField({
      name: 'thumbnailEnabled',
      title: 'Thumbnail Generation Enabled',
      type: 'boolean',
      fieldset: 'aiGeneration',
      description: 'Generate custom thumbnails for videos and shorts',
      initialValue: true,
    }),
    defineField({
      name: 'infographicInstructions',
      title: 'Infographic Instructions',
      type: 'array',
      fieldset: 'aiGeneration',
      description:
        'Prompts sent for infographic generation. Each instruction produces one infographic per research run',
      of: [{ type: 'string' }],
      initialValue: [
        'Create a high-level architecture overview diagram',
        'Create a comparison chart of key features and alternatives',
        'Create a step-by-step workflow diagram',
        'Create a timeline of key developments and milestones',
        'Create a pros and cons visual summary',
      ],
    }),
    defineField({
      name: 'targetVideoDurationSec',
      title: 'Target Video Duration (sec)',
      type: 'number',
      fieldset: 'aiGeneration',
      description: 'Target duration for generated videos in seconds. Scripts are calibrated to this length',
      initialValue: 180,
    }),
    defineField({
      name: 'sceneCountMin',
      title: 'Scene Count Min',
      type: 'number',
      fieldset: 'aiGeneration',
      description: 'Minimum number of scenes per video',
      initialValue: 8,
    }),
    defineField({
      name: 'sceneCountMax',
      title: 'Scene Count Max',
      type: 'number',
      fieldset: 'aiGeneration',
      description: 'Maximum number of scenes per video. Keeps videos focused and within duration targets',
      initialValue: 15,
    }),

    // ─── Audio ───────────────────────────────────────────────────────────
    defineField({
      name: 'elevenLabsVoiceId',
      title: 'ElevenLabs Voice ID',
      type: 'string',
      fieldset: 'audio',
      description: 'ElevenLabs voice ID for text-to-speech narration',
      initialValue: 'pNInz6obpgDQGcFmaJgB',
    }),

    // ─── Distribution ────────────────────────────────────────────────────
    defineField({
      name: 'youtubeEnabled',
      title: 'YouTube Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Upload videos to YouTube',
      initialValue: true,
    }),
    defineField({
      name: 'twitterEnabled',
      title: 'Twitter/X Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Post to Twitter/X',
      initialValue: true,
    }),
    defineField({
      name: 'linkedinEnabled',
      title: 'LinkedIn Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Post to LinkedIn',
      initialValue: true,
    }),
    defineField({
      name: 'tiktokEnabled',
      title: 'TikTok Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Post to TikTok (off by default — needs API approval)',
      initialValue: false,
    }),
    defineField({
      name: 'instagramEnabled',
      title: 'Instagram Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Post to Instagram (off by default — needs FB Business)',
      initialValue: false,
    }),
    defineField({
      name: 'blueskyEnabled',
      title: 'Bluesky Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Post to Bluesky',
      initialValue: true,
    }),
    defineField({
      name: 'newsletterEnabled',
      title: 'Newsletter Enabled',
      type: 'boolean',
      fieldset: 'distribution',
      description: 'Send newsletter emails via Resend',
      initialValue: true,
    }),
    defineField({
      name: 'youtubeUploadVisibility',
      title: 'YouTube Upload Visibility',
      type: 'string',
      fieldset: 'distribution',
      description:
        "Default visibility for uploaded YouTube videos. Use 'private' for testing, 'unlisted' for review, 'public' for production",
      initialValue: 'private',
      options: {
        list: [
          { title: 'Private', value: 'private' },
          { title: 'Unlisted', value: 'unlisted' },
          { title: 'Public', value: 'public' },
        ],
      },
    }),
    defineField({
      name: 'youtubeChannelId',
      title: 'YouTube Channel ID',
      type: 'string',
      fieldset: 'distribution',
      description: 'Your YouTube channel ID — used for analytics and upload targeting',
      initialValue: '',
    }),
    defineField({
      name: 'youtubeDescriptionTemplate',
      title: 'YouTube Description Template',
      type: 'text',
      fieldset: 'distribution',
      description: 'Template for YouTube video descriptions. Use {{title}} and {{summary}} placeholders',
      initialValue:
        '{{title}}\n\n{{summary}}\n\n🔗 Learn more at https://codingcat.dev\n\n#webdev #coding #programming',
    }),
    defineField({
      name: 'youtubeDefaultTags',
      title: 'YouTube Default Tags',
      type: 'array',
      fieldset: 'distribution',
      description: 'Default tags applied to all uploaded YouTube videos. Topic-specific tags are added by AI',
      of: [{ type: 'string' }],
      initialValue: ['web development', 'coding', 'programming', 'tutorial', 'codingcat'],
    }),
    defineField({
      name: 'notificationEmails',
      title: 'Notification Emails',
      type: 'array',
      fieldset: 'distribution',
      description: 'Email addresses that receive notifications when a new video is published',
      of: [{ type: 'string' }],
      initialValue: ['alex@codingcat.dev'],
    }),
    defineField({
      name: 'resendFromEmail',
      title: 'Resend From Email',
      type: 'string',
      fieldset: 'distribution',
      description: 'Sender email address for notification emails via Resend',
      initialValue: 'content@codingcat.dev',
    }),

    // ─── Sponsor ─────────────────────────────────────────────────────────
    defineField({
      name: 'cooldownDays',
      title: 'Cooldown Days',
      type: 'number',
      fieldset: 'sponsor',
      description: 'Days to wait before contacting a sponsor again after the last outreach',
      initialValue: 14,
    }),
    defineField({
      name: 'rateCardTiers',
      title: 'Rate Card Tiers',
      type: 'array',
      fieldset: 'sponsor',
      description:
        'Sponsorship pricing tiers shown in outreach emails. Each tier has a name, description, and price',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'name',
              title: 'Name',
              type: 'string',
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'string',
            }),
            defineField({
              name: 'price',
              title: 'Price',
              type: 'number',
            }),
          ],
        },
      ],
      initialValue: [
        { _type: 'object', _key: 'starter', name: 'starter', description: '5k-10k impressions', price: 500 },
        { _type: 'object', _key: 'growth', name: 'growth', description: '10k-50k impressions', price: 1500 },
        { _type: 'object', _key: 'premium', name: 'premium', description: '50k+ impressions', price: 3000 },
      ],
    }),
    defineField({
      name: 'outreachEmailTemplate',
      title: 'Outreach Email Template',
      type: 'text',
      fieldset: 'sponsor',
      description: 'Template for automated sponsor outreach emails. Use {{companyName}} for personalization',
      initialValue: 'Hi {{companyName}},\n\nI run CodingCat.dev...',
    }),
    defineField({
      name: 'maxOutreachPerRun',
      title: 'Max Outreach Per Run',
      type: 'number',
      fieldset: 'sponsor',
      description: 'Maximum sponsor emails to send per cron run',
      initialValue: 10,
    }),

    // ─── Brand ───────────────────────────────────────────────────────────
    defineField({
      name: 'brandPrimary',
      title: 'Brand Primary',
      type: 'string',
      fieldset: 'brand',
      description: 'Primary accent color',
      initialValue: '#7c3aed',
    }),
    defineField({
      name: 'brandBackground',
      title: 'Brand Background',
      type: 'string',
      fieldset: 'brand',
      description: 'Background color',
      initialValue: '#000000',
    }),
    defineField({
      name: 'brandText',
      title: 'Brand Text',
      type: 'string',
      fieldset: 'brand',
      description: 'Text color',
      initialValue: '#ffffff',
    }),

    // ─── Legacy ──────────────────────────────────────────────────────────
    defineField({
      name: 'awsRegion',
      title: 'AWS Region',
      type: 'string',
      fieldset: 'legacy',
      description: 'Legacy: Remotion Lambda AWS region',
      deprecated: { reason: 'Migrated to Cloudflare Workers. Remove after v2 migration.' },
    }),
    defineField({
      name: 'remotionFunctionName',
      title: 'Remotion Function Name',
      type: 'string',
      fieldset: 'legacy',
      description: 'Legacy: Remotion Lambda function name',
      deprecated: { reason: 'Migrated to Cloudflare Workers. Remove after v2 migration.' },
    }),
    defineField({
      name: 'remotionServeUrl',
      title: 'Remotion Serve URL',
      type: 'string',
      fieldset: 'legacy',
      description: 'Legacy: Remotion bundle URL',
      deprecated: { reason: 'Migrated to Cloudflare Workers. Remove after v2 migration.' },
    }),
    defineField({
      name: 'gcsBucketName',
      title: 'GCS Bucket Name',
      type: 'string',
      fieldset: 'legacy',
      description: 'Legacy: GCS bucket name',
      deprecated: { reason: 'Migrated to R2. Remove after v2 migration.' },
    }),
    defineField({
      name: 'gcsProjectId',
      title: 'GCS Project ID',
      type: 'string',
      fieldset: 'legacy',
      description: 'Legacy: GCS project ID',
      deprecated: { reason: 'Migrated to R2. Remove after v2 migration.' },
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Engine Config' };
    },
  },
});
