name: dev-main-build

on:
  push:
    branches: [ dev ]
    paths: 'frontend/main'
  pull_request:
    branches: [ dev ]
    paths: 'frontend/main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend/main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
