name: dev-main-build
environment: dev

on:
  push:
    branches: [ dev ]
    paths: 'frontend/main'
  pull_request:
    branches: [ dev ]
    paths: 'frontend/main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend/main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - name: Deploy dev
        uses: amondnet/vercel-action@v19
        id: vercel-action-staging
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
